import * as Tone from "tone";

//Function for playing intervals
/*
 * gamemode: gamemode chosen by user
 * newNoteList: new note list generated by listShift.js
 * rootNote: root note generated by randomizer in Game.jsx
 * intNote: interval note generated by randomizer in Game.jsx
 */
function playInterval(gamemode, newNoteList, rootNote, intNote) {
  //set up note player
  const synth = new Tone.Synth().toDestination();
  Tone.getTransport().start();
  let pitch = 4;

  //Play the rootNote
  Tone.getTransport().schedule((time) => {
    synth.triggerAttackRelease(newNoteList[rootNote][0] + "4", "8n", time);
  }, "+0"); // 0 seconds from now

  //Depending on the gamemode, logic will change for interval note pitch
  if (gamemode === "Ascending") {
    if (
      newNoteList[intNote][1] < newNoteList[rootNote][1] ||
      newNoteList[intNote][1] === 12
    ) {
      pitch = 5;
    } else {
      pitch = 4;
    }
    Tone.getTransport().schedule((time) => {
      synth.triggerAttackRelease(
        `${newNoteList[intNote][0]}${pitch}`,
        "8n",
        time,
      );
    }, "+1"); // 1 second from now
  } else if (gamemode === "Descending") {
    if (
      newNoteList[intNote][1] > newNoteList[rootNote][1] ||
      newNoteList[intNote][1] === 12
    ) {
      pitch = 3;
    } else {
      pitch = 4;
    }
    Tone.getTransport().schedule((time) => {
      synth.triggerAttackRelease(newNoteList[intNote][0] + "4", "8n", time);
    }, "+1"); // 1 second from now
  }
}

export default playInterval;
